//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINHLUAN
    {
        public int MaBL { get; set; }
        public string MaPH { get; set; }
        public string MaKH { get; set; }
        public string NDBL { get; set; }
        public Nullable<int> DanhGia { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
