//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATPHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DATPHONG()
        {
            this.DATDICHVUs = new HashSet<DATDICHVU>();
        }
    
        public string MaDP { get; set; }
        public string MaKH { get; set; }
        public string MaPH { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> DatCoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATDICHVU> DATDICHVUs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
