//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuThayDoi
    {
        public int Id { get; set; }
        public string MaKH { get; set; }
        public string TruongThayDoi { get; set; }
        public string GiaTriCu { get; set; }
        public string GiaTriMoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoi { get; set; }
        public string NguoiThayDoi { get; set; }
    }
}
